version: "3.8"

services:
  web:
    build: .
    container_name: brewnotes-web
    env_file: .env
    # If you have entrypoint.sh, use that; otherwise keep the gunicorn line:
    # command: ["/code/entrypoint.sh"]
    command: >
      gunicorn brewnotes_vps.wsgi:application
      -b 0.0.0.0:8000
      --workers 3
      --timeout 60
      --access-logfile -
      --error-logfile -
      --log-level debug
      --capture-output
      --forwarded-allow-ips="*"
    ports:
      - "3050:8000"           # host:container (LAN-accessible)
    restart: unless-stopped
    networks:
      - coolify
    # For production, avoid bind-mounting the source. Uncomment only if you need live-reload style dev.
    # volumes:
    #   - .:/code

networks:
  coolify:
    external: true
    name: coolify
