version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: brewnotes:latest
    container_name: brewnotes-web
    working_dir: /app
    # entrypoint.sh handles migrations, collectstatic, and starts Gunicorn
    command: >
      bash -lc "bash entrypoint.sh"
    env_file:
      - .env
    ports:
      - "3050:8000"
    restart: unless-stopped
    networks:
      - coolify
    # Healthcheck hits the root; adjust to /health if you add one later
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    # If your DB runs as a separate container on the same network, you can
    # add it to depends_on. For now it's omitted because your DB is external.

networks:
  coolify:
    external: true
