# Generated by Django 4.2.23 on 2025-07-23 14:51

from django.db import migrations


def load_initial_data(apps, schema_editor):
    DrinkType = apps.get_model('notes', 'DrinkType')

    # Load drink types
    drink_types = [
        ('IPA', 'Hoppy beer style with strong bitterness'),
        ('Stout', 'Dark roasted malt, rich and creamy'),
        ('Pale Ale', 'Balanced beer with moderate hops'),
        ('Lager', 'Crisp, clean beer with light flavor'),
        ('Porter', 'Dark beer with chocolate and coffee notes'),
        ('Wheat Beer', 'Light, cloudy beer with wheat malt'),
        ('Sour Ale', 'Tart beer with fruity or funky flavors'),
        ('Cider', 'Fermented apple juice, sweet or dry'),
        ('Perry', 'Fermented pear juice, similar to cider'),
        ('Session IPA', 'Lower-alcohol IPA with hoppy character'),
        ('Pilsner', 'Light, golden beer with crisp finish'),
        ('Amber Ale', 'Malty beer with caramel undertones'),
        ('Fruit Cider', 'Cider infused with fruit flavors'),
        ('Barleywine', 'Strong, sweet beer with high alcohol')
    ]
    for name, desc in drink_types:
        DrinkType.objects.get_or_create(name=name, description=desc)


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0001_initial'),
    ]
    operations = [migrations.RunPython(load_initial_data)]
