# Generated by Django 4.2.23 on 2025-08-03 19:33
from django.db import migrations


def load_initial_data(apps, schema_editor):
    DrinkType = apps.get_model('notes', 'DrinkType')
    Ingredient = apps.get_model('notes', 'Ingredients')

    drink_types = [
        ('IPA', 'Hoppy beer style with strong bitterness'),
        ('Stout', 'Dark roasted malt, rich and creamy'),
        ('Pale Ale', 'Balanced beer with moderate hops'),
        ('Lager', 'Crisp, clean beer with light flavor'),
        ('Porter', 'Dark beer with chocolate and coffee notes'),
        ('Wheat Beer', 'Light, cloudy beer with wheat malt'),
        ('Sour Ale', 'Tart beer with fruity or funky flavors'),
        ('Cider', 'Fermented apple juice, sweet or dry'),
        ('Perry', 'Fermented pear juice, similar to cider'),
        ('Session IPA', 'Lower-alcohol IPA with hoppy character'),
        ('Pilsner', 'Light, golden beer with crisp finish'),
        ('Amber Ale', 'Malty beer with caramel undertones'),
        ('Fruit Cider', 'Cider infused with fruit flavors'),
        ('Barleywine', 'Strong, sweet beer with high alcohol')
    ]
    for name, desc in drink_types:
        DrinkType.objects.get_or_create(name=name, description=desc)

    ingredients = [
        {
            'name': 'Pale Malt',
            'description': 'Base malt for most beer styles'
        },
        {
            'name': 'Cascade Hops',
            'description': 'Floral  American hops'
        },
        {
            'name': 'American Ale Yeast',
            'description': 'Clean, well-attenuating yeast'
        },
        {
            'name': 'Malted Barley',
            'description': 'The primary fermentable sugar source for beer, available in various types like Pilsner, Pale, Crystal, Chocolate, and Black malts, each contributing unique flavors.'
        },
        {
            'name': 'Hops (Bittering)',
            'description': 'Hops added early in the boil for bitterness, such as Magnum or Horizon.'
        },
        {
            'name': 'Hops (Aroma)',
            'description': 'Hops added late in the boil or during dry hopping for their aromatic compounds and flavors, including citrusy (Citra, Cascade), piney (Chinook), floral (East Kent Goldings), or tropical (Mosaic, Galaxy) notes.'
        },
        {
            'name': 'Hops (Dual-Purpose)',
            'description': 'Hops that provide both bitterness and aroma, like Centennial or Challenger.'
        },
        {
            'name': 'Yeast (Ale - Saccharomyces cerevisiae)',
            'description': 'Top-fermenting yeast strains that produce diverse flavor compounds (esters, phenols) at warmer temperatures (15-24°C), suitable for various ale styles. Examples include American Ale yeast, British Ale yeast, Belgian Ale yeast, and Kveik yeast.'
        },
        {
            'name': 'Yeast (Lager - Saccharomyces pastorianus)',
            'description': 'Bottom-fermenting yeast strains that work at colder temperatures (7-13°C), resulting in clean, crisp, and subtle flavor profiles, ideal for lagers.'
        },
        {
            'name': 'Yeast (Wild - Brettanomyces)',
            'description': 'Yeast strains that can introduce funky, earthy, or "barnyard" notes, often used in specialty sour beers and ciders.'
        },
        {
            'name': 'Water',
            'description': 'The most voluminous ingredient, whose mineral content significantly impacts mash chemistry, yeast health, and the final beer\'s taste and mouthfeel.'
        },
        {
            'name': 'Apples (or other fruit)',
            'description': 'The primary fermentable sugar source for cider, with the choice of apple varieties (sweet, tart, bittersharp, bittersweet) or other fruits dictating the cider\'s balance of sweetness, acidity, and tannins.'
        },
        {
            'name': 'Yeast Nutrient',
            'description': 'Supplements (e.g., Diammonium Phosphate (DAP)) providing nitrogen, vitamins, and minerals to ensure healthy yeast growth and efficient fermentation, especially in high-gravity worts or juices.'
        },
        {
            'name': 'Yeast Food',
            'description': 'A complete blend of nutrients for optimal yeast health during fermentation.'
        },
        {
            'name': 'Irish Moss / Whirlfloc',
            'description': 'A fining agent used in the boil to help proteins coagulate and settle out, leading to clearer beer.'
        },
        {
            'name': 'Finings (Post-Fermentation)',
            'description': 'Clarifying agents added after fermentation to remove haze-causing particles. Examples include Isinglass, Gelatin, Bentonite, Silica-based finings (e.g., Kieselsol), and PVPP (Polyclar).'
        },
        {
            'name': 'Priming Sugar',
            'description': 'A fermentable sugar (e.g., dextrose/corn sugar, sucrose/table sugar) added before packaging to create natural carbonation through secondary fermentation in bottles or kegs.'
        },
        {
            'name': 'Carbonation Dioxide (CO2)',
            'description': 'Used for force carbonating beer or cider in kegs, providing a controlled and rapid method for achieving desired carbonation levels.'
        }

    ]
    for item in ingredients:
        Ingredient.objects.get_or_create(
            name=item['name'],
            defaults={
                'description': item['description']
            }
        )


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0001_initial'),
    ]
    operations = [migrations.RunPython(load_initial_data)]
