# Generated by Django 4.2.23 on 2025-08-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_load_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
