# Generated by Django 4.2.23 on 2025-08-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Select ingredients for this recipe', related_name='recipes', to='notes.ingredient'),
        ),
    ]
