# Generated by Django 4.2.23 on 2025-08-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_recipe_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='notes',
            new_name='brewing_notes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='testing_notes',
            field=models.TextField(blank=True, help_text='Brewing observations, adjustments, or tasting notes'),
        ),
    ]
