# Generated by Django 4.2.23 on 2025-08-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_rename_notes_recipe_brewing_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinktype',
            name='user',
            field=models.ForeignKey(default=1, help_text='Creator of this drink type', on_delete=django.db.models.deletion.CASCADE, related_name='drink_types', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(default=1, help_text='Creator of this ingredient', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
