# Generated by Django 4.2.23 on 2025-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_remove_recipe_ingredients_recipeingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('ml', 'millilitres')], help_text='Measurement unit', max_length=2),
        ),
    ]
