# Generated by Django 4.2.23 on 2025-08-18 14:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
